### ISSUE TITLE
Plan to support sequelize v6?

### ISSUE THREAD

**Issue by EyePulp** [valtlfelipe/hapi-sequelizejs#40]
Howdy;
I haven't done much testing, other than seeing the current version of hapi-sequelizejs didn't work right off the bat with with the [sequelize v6 beta](https://github.com/sequelize/sequelize#v6-beta-release).  

I'm curious if it's on the roadmap to support it, and if it's just a matter of finding the time.  If I get some free time I can try to work through it, but that may not be for several weeks.

Thanks for a useful plugin, regardless.

**Comment by valtlfelipe** [comment]
Hi @EyePulp!

I was going to look at this today, but I saw you just opened a PR, thanks! That's awesome!

As I can understand, sequelize v6 just got out of the beta, right?

I will have a look at your PR later today, but since this is a major change, I will test it further and pretende to release a new version of the plugin until the end of this week :)

**Comment by EyePulp** [comment]
@valtlfelipe Yes, it looks like it just came out of beta today or last night - it was still in beta when I opened this issue yesterday!

My edits ended up being fairly minor -- two lines to get all the tests to pass. Please make any changes you feel necessary.  I'm now running the PR branch in a project for local testing, and it's working ok.

Thanks again!

**Comment by valtlfelipe** [comment]
Alright, awesome! 😄

**Comment by valtlfelipe** [comment]
Just published `4.2.0` with your changes.

Thanks again for your PR and your amazing contribution! You rock!

**Comment by EyePulp** [comment]
@valtlfelipe Great news, thanks!  Glad we could help with some support.  We appreciate your work.
