### ISSUE TITLE
Any plans to support sequelize v4?

### ISSUE THREAD

**Issue by murnun** [valtlfelipe/hapi-sequelizejs#5]

**Comment by valtlfelipe** [comment]
Yes! It is in my todo list.
I will start to work on it soon.

**Comment by alexb-uk** [comment]
Hi, I'm starting a new project and wouldn't want to use an old version of Sequelize but would like to make use of your library if possible. Partly because I've never used Sequelize before and hence don't want to learn an out of date API etc.

@valtlfelipe Do you know yet how much work would be involved to update hapi-sequelizejs to be compatible with Sequelize v4? Is it something I might be able to help with?

Thanks

**Comment by valtlfelipe** [comment]
@alexb-uk just created PR #6 with the todo's, and I will be working on it during this week.

You can expect a new release by the start of next week with support to sequelize version 4! :smile:

**Comment by jberall** [comment]
I'm curious.
With the release of v17 have you tested the extension?

**Comment by valtlfelipe** [comment]
@jberall 

The plugin does not support hapi 17 yet. There are some changes to the plugin API and the minimum node version has changed. I'm working on it to support v17.

Just released [0.2.0](https://github.com/valtlfelipe/hapi-sequelizejs/releases/tag/0.2.0) with support to Sequelize v4.

**Comment by jberall** [comment]
Awesome


Jonathan Berall
